Repository renpy/renpy, pull requests merged in 2023-07, with the labels that each got.

#4797 Enable jump/call expression to local labels
  renpy/ast.py
  renpy/exports.py
  renpy/parser.py
  sphinx/source/changelog.rst
  sphinx/source/label.rst
Labels: enhancement

#4749 Add last_say function.
  renpy/exports.py
Labels: enhancement

#4745 Detect multipart strings marked for translation
  renpy/translation/scanstrings.py
Labels: enhancement

#4813 Update the list of operators in the lexer
  renpy/lexer.py
Labels: other

#4820 Update layeredimage.predict_all to None
  renpy/common/00layeredimage.rpy
Labels: other

#4809 Tweaks to renpy.last_say
  renpy/display/screen.py
  renpy/exports.py
Labels: enhancement

#4821 doc: readd information that went missing during the rewrite
  sphinx/source/layeredimage.rst
Labels: documentation

#4709 Support position (absolute) everywhere
  renpy/common/00action_other.rpy
  renpy/common/00splines.rpy
  renpy/display/dragdrop.py
  renpy/display/motion.py
  renpy/display/render.pyx
  renpy/gl2/live2d.py
  sphinx/source/atl.rst
  sphinx/source/changelog.rst
  sphinx/source/style_properties.rst
Labels: enhancement

#4843 Fix absolute.slots to __slots__
  renpy/display/core.py
Labels: other

#4844 Absolute compute
  renpy/common/00action_other.rpy
  renpy/common/00splines.rpy
  renpy/display/accelerator.pyx
  renpy/display/core.py
  renpy/display/displayable.py
  renpy/display/dragdrop.py
  renpy/display/layout.py
  renpy/display/motion.py
  renpy/display/render.pyx
  renpy/display/transform.py
  renpy/gl2/live2d.py
Labels: enhancement

#4583 Make renpy.confirm instead of yesno_screen
  renpy/common/00action_other.rpy
  renpy/common/00layout.rpy
  renpy/exports.py
  sphinx/source/screen_special.rst
Labels: enhancement
