Repository renpy/renpy, pull requests merged in 2023-10, with the labels that each got.

#5050 Add warnings and deprecated sections for image manipulators
  renpy/display/im.py
  sphinx/source/im.rst
Labels: documentation

#5045 Clarify clipping behaviour as it relates to layers and Layer
  renpy/display/layout.py
  sphinx/source/config.rst
Labels: documentation

#5059 Prevent creation of a "store" substore
  renpy/python.py
Labels: crash or exception

#4473 Action mixins
  renpy/common/00action_data.rpy
  sphinx/source/screen_actions.rst
Labels: enhancement

#5067 Changelog mixins
  sphinx/source/changelog.rst
Labels: documentation

#5073 Re-add the pass keyword to the layeredimage language
  renpy/common/00layeredimage.rpy
Labels: enhancement

#5055 add the `LocalVariableValue` action
  renpy/common/00barvalues.rpy
Labels: enhancement

#5064 Factorize and improve some Barvalue subclasses
  renpy/common/00barvalues.rpy
Labels: enhancement

#5057 Add lint toggles
  launcher/game/front_page.rpy
  launcher/game/preferences.rpy
  renpy/lint.py
Labels: enhancement

#4839 `copy_properties` method for custom screen statements
  renpy/sl2/slparser.py
Labels: enhancement
