Repository renpy/renpy, pull requests merged in 2023-12, with the labels that each got.

#5099 Standalone parameterinfo
  renpy/ast.py
  renpy/atl.py
  renpy/display/screen.py
  renpy/lint.py
  renpy/parser.py
  renpy/py2analysis.py
  renpy/py3analysis.py
Labels: other

#5084 Document that renpy.dynamic supports variables in stores
  renpy/exports.py
Labels: documentation

#5160 Fix interpolation of move transitions wrt the position type
  renpy/display/movetransition.py
Labels: crash or exception

#5168 Fix #5165
  renpy/exports.py
  sphinx/source/other.rst
Labels: documentation

#5150 Lint check_conflicting_properties
  renpy/lint.py
Labels: unintended behavior

#4841 let a viewport/vpgrid respect the force_step argument of a used ui.adjustment
  renpy/display/viewport.py
Labels: enhancement
