Repository renpy/renpy, pull requests merged in 2023-11, with the labels that each got.

#3695 Open/create projects.txt from the launcher preferences
  launcher/game/preferences.rpy
Labels: enhancement

#4545 Add a type check on data saved in persistent
  renpy/compat/pickle.py
  renpy/persistent.py
Labels: enhancement

#4606 Bring list operator dunders in accordance with the datamodel
  renpy/revertable.py
Labels: unintended behavior

#5130 Guarantee that invoke_in_main_thread calls are sequential
  renpy/exports.py
Labels: documentation

#4495 docs: Add note for StylePreference about update event getting called
  renpy/common/00stylepreferences.rpy
Labels: documentation

#4561 Ensure ios_create uses the target project's information
  launcher/game/ios.rpy
Labels: platform-ios

#4716 Repeal the annotations future and expand the `rpy python` statement
  renpy/ast.py
  renpy/parser.py
  renpy/python.py
  renpy/script.py
  renpy/sl2/slast.py
  sphinx/source/changelog.rst
  sphinx/source/incompatible.rst
Labels: other

#4799 Forbid pos-only and required kw-only parameters in ATL
  renpy/common/00compat.rpy
  renpy/config.py
  renpy/parser.py
Labels: enhancement, crash or exception

#5123 Add a general coordinate type and allow mixed-type ATL interpolation
  renpy/atl.py
  renpy/common/00compat.rpy
  renpy/config.py
  renpy/display/core.py
  renpy/display/motion.py
  renpy/display/transform.py
  sphinx/source/atl.rst
  sphinx/source/changelog.rst
  sphinx/source/incompatible.rst
  sphinx/source/style_properties.rst
Labels: enhancement
