Repository renpy/renpy, pull requests merged in 2023-08, with the labels that each got.

#4904 Various changes to the ATL page
  sphinx/source/atl.rst
Labels: documentation

#4900 Fix occurrences of *args following a kwarg in calls
  renpy/common/00action_control.rpy
  renpy/common/00action_menu.rpy
  renpy/common/00layeredimage.rpy
  renpy/defaultstore.py
  renpy/display/anim.py
  renpy/display/focus.py
  renpy/exports.py
  renpy/sl2/slast.py
Labels: other

#4893 Sensitiveness and selectedness of action lists
  renpy/common/00action_other.rpy
  sphinx/source/screen_actions.rst
Labels: documentation

#4927 respect "renpy.store._autosave"
  renpy/loadsave.py
Labels: unintended behavior
