Repository renpy/renpy, pull requests merged in 2023-01, with the labels that each got.

#4192 Undocument config.overlay_functions
  sphinx/source/config.rst
Labels: documentation

#4206 Remove remaining gl2 references
  renpy/display/transition.py
  sphinx/source/displayables.rst
  sphinx/source/im.rst
  sphinx/source/live2d.rst
Labels: documentation

#4205 Fix wrong config variable name
  sphinx/source/store_variables.rst
Labels: documentation

#3595 New screen clauses
  renpy/common/000statements.rpy
  renpy/display/screen.py
Labels: enhancement

#3601 Document new clauses for show screen and other statements
  renpy/display/screen.py
  sphinx/source/screens.rst
Labels: documentation

#4218 Add a entry for config.pad_bindings
  sphinx/source/config.rst
Labels: documentation

#4216 Add an entry for config.perspective
  sphinx/source/3dstage.rst
  sphinx/source/config.rst
Labels: documentation

#4214 Undocument config.editor and document Shift+E
  sphinx/source/developer_tools.rst
Labels: documentation

#4215 Add a formal doc entry for config.console
  sphinx/source/config.rst
Labels: documentation

#4213 Unmixup config.language and config.default_language
  sphinx/source/config.rst
  sphinx/source/translation.rst
Labels: documentation

#4212 Include functions intended to be documented
  sphinx/source/android.rst
Labels: documentation

#4217 Avoid undocumented config variables in examples
  sphinx/source/config.rst
  sphinx/source/file_python.rst
  sphinx/source/screens.rst
Labels: documentation

#4224 Improve and secure the documented signature of renpy.show
  renpy/exports.py
  sphinx/source/config.rst
Labels: documentation

#4227 Secure documented signatures
  renpy/color.py
  renpy/config.py
  renpy/display/imagelike.py
  renpy/display/movetransition.py
  renpy/display/render.pyx
  renpy/display/transition.py
  renpy/exports.py
  renpy/sl2/slparser.py
  renpy/text/text.py
  renpy/ui.py
Labels: documentation

#4226 Document name-munging more visually and add warning for f-strings incompatibility
  sphinx/source/language_basics.rst
Labels: documentation

#4144 Classify actions as functions
  sphinx/game/doc.py
Labels: documentation generation

#4246 [docs] Elaborate on layer specification in camera statement description
  sphinx/source/3dstage.rst
Labels: documentation

#4251 Remove wrong example and move things around
  sphinx/source/translation.rst
Labels: documentation

#4229 Ban object's __init__ docstring from our documentation
  sphinx/game/doc.py
Labels: documentation generation

#4250 Variables documentation
  renpy/exports.py
  sphinx/source/config.rst
  sphinx/source/custom_text_tags.rst
  sphinx/source/gesture.rst
  sphinx/source/preferences.rst
  sphinx/source/side_image.rst
  sphinx/source/store_variables.rst
Labels: documentation

#3929 Add lint reachability analysis
  renpy/lint.py
Labels: enhancement
