Repository renpy/renpy, pull requests merged in 2023-05, with the labels that each got.

#4607 Remove warning about software rendererers
  sphinx/source/atl.rst
Labels: documentation

#4611 Document LayeredImage.add
  renpy/common/00layeredimage.rpy
Labels: documentation

#4576 Allow None transition for ShowMenu
  renpy/common/00action_menu.rpy
Labels: enhancement

#4674 Fix interpolation example block
  sphinx/source/atl.rst
Labels: documentation

#4680 Make absolute a float again
  renpy/display/core.py
Labels: other
