Repository renpy/renpy, pull requests merged in 2023-02, with the labels that each got.

#4304 Add an example of currying a character callback
  sphinx/source/character_callbacks.rst
Labels: documentation

#4301 Update the Style page
  renpy/character.py
  sphinx/source/developer_tools.rst
  sphinx/source/style.rst
Labels: documentation

#4288 Upgrade the fixed rollback documentation to strip obsolete functions
  renpy/ui.py
  sphinx/source/save_load_rollback.rst
Labels: documentation

#3850 Make spacing relative in grids (and vpgrids)
  renpy/common/00compat.rpy
  renpy/config.py
  renpy/display/layout.py
  renpy/display/viewport.py
Labels: enhancement

#3730 Add a dict for font aliases
  renpy/config.py
  renpy/text/font.py
  renpy/text/text.py
  sphinx/source/config.rst
  sphinx/source/text.rst
Labels: enhancement

#4322 Changelog
  sphinx/source/changelog.rst
Labels: documentation

#4316 Add break and continue to the screen language for loop
  renpy/sl2/slast.py
  renpy/sl2/slparser.py
Labels: enhancement - hour

#4315 Add renpy.is_pixel_opaque
  renpy/exports.py
Labels: enhancement

#4349 Doc misc (tweaks and fixes)
  renpy/common/00action_other.rpy
  sphinx/source/layeredimage.rst
  sphinx/source/python.rst
  sphinx/source/style.rst
Labels: documentation

#4326 Include an example of a proper usage of time_warp in the docs of ImageDissolve
  renpy/display/transition.py
Labels: documentation

#4348 Modernize the `inspect` module and fix subclasses of RevObject not overriding __init__
  sphinx/game/doc.py
  sphinx/game/script.rpy
Labels: documentation generation

#4324 Cutscene and loop for web
  renpy/audio/audio.py
  renpy/audio/webaudio.py
  renpy/common/00webvideo.rpy
  renpy/common/_audio.js
  sphinx/source/movie.rst
Labels: web

#4370 Document #4316
  sphinx/source/changelog.rst
  sphinx/source/screens.rst
Labels: documentation

#4369 Fix classes signatures in the documentation (again)
  sphinx/game/doc.py
  sphinx/game/script.rpy
Labels: documentation generation

#4376 Upgrade example of config variable definition
  sphinx/source/config.rst
Labels: documentation

#4382 Enable ClearFocus and renpy.clear_capture_focus to clear all focuses at once
  renpy/common/00action_other.rpy
  renpy/display/focus.py
Labels: enhancement

#4357 Document mipmap specifically in transition parameters
  renpy/display/transition.py
Labels: documentation

#4313 Implement `rpy monologue none`
  renpy/lexer.py
  renpy/parser.py
Labels: enhancement

#4401 Doc and changelog monologue none
  sphinx/source/changelog.rst
  sphinx/source/dialogue.rst
Labels: documentation
