Repository renpy/renpy, pull requests merged in 2023-06, with the labels that each got.

#4657 Dereference utter_restart and move reload-related functions to the reload section
  renpy/exports.py
  sphinx/source/developer_tools.rst
Labels: documentation

#4700 Fix mouse_move documentation
  renpy/common/00action_other.rpy
  renpy/common/00preferences.rpy
  sphinx/source/preferences.rst
Labels: documentation

#4706 Extend the system cursor preference to config.mouse_displayable
  renpy/common/00preferences.rpy
  renpy/display/core.py
  sphinx/source/changelog.rst
  sphinx/source/preferences.rst
Labels: enhancement, duration - hour

#4738 Tweak the Movie callable documentation
  renpy/display/video.py
Labels: documentation

#4751 Tweak docstrings for transitions
  renpy/common/00definitions.rpy
  renpy/display/movetransition.py
  renpy/display/transition.py
Labels: documentation

#4778 Prevent rare divide by zero in drag/drop
  renpy/display/dragdrop.py
Labels: crash or exception

#4794 Add the screen property directive
  sphinx/source/renpydoc.py
  sphinx/source/screens.rst
Labels: documentation, documentation generation
