Repository renpy/renpy, pull requests merged in 2024-01, with the labels that each got.

#4995 Various improvements around warpers
  renpy/common/00definitions.rpy
  renpy/display/movetransition.py
  renpy/display/transition.py
  sphinx/source/atl.rst
Labels: documentation

#5235 Better document conflicting properties
  sphinx/source/changelog.rst
  sphinx/source/incompatible.rst
Labels: documentation

#5036 Treat string interpolations as Python expressions
  renpy/common/00compat.rpy
  renpy/config.py
  renpy/substitutions.py
  sphinx/source/changelog.rst
  sphinx/source/incompatible.rst
  sphinx/source/text.rst
Labels: enhancement

#5249 Use the :file: role a lot
  sphinx/source/audio.rst
  sphinx/source/build.rst
  sphinx/source/config.rst
  sphinx/source/displayables.rst
  sphinx/source/displaying_images.rst
  sphinx/source/environment_variables.rst
  sphinx/source/gui.rst
  sphinx/source/layeredimage.rst
  sphinx/source/live2d.rst
  sphinx/source/persistent.rst
  sphinx/source/quickstart.rst
  sphinx/source/rooms.rst
  sphinx/source/save_load_rollback.rst
  sphinx/source/skins.rst
  sphinx/source/splashscreen_presplash.rst
  sphinx/source/style_properties.rst
  sphinx/source/text.rst
  sphinx/source/translating_renpy.rst
  sphinx/source/translation.rst
  sphinx/source/voice.rst
Labels: documentation

#5252 Fix polar anchor and some ATL docs improvements
  renpy/atl.py
  renpy/display/transform.py
  sphinx/source/atl.rst
Labels: documentation, unintended behavior

#4924 Implement AlphaMask using shader
  renpy/common/_shaders.rpym
  renpy/display/layout.py
Labels: enhancement

#4848 Enable the _layer parameter for the menu statement and add config.nvl_choice_layer
  renpy/config.py
  renpy/exports.py
Labels: enhancement

#5129 doc: Clarify renpy.pause's parameters
  renpy/exports.py
Labels: documentation
